src/deformaldehyde/dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path(r'tag/<slug:tag_name>.html', views.TagDetailView.as_view(), name='tag_detail'),
    path(r'area/<slug:tag_name>.html', views.AreaTagView.as_view(), name='area_tag'),
    path(r'category/<slug:category_name>.html', views.ArchiveView.as_view(), name='article_category'),
]

src/deformaldehyde/deformaldehyde/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap

from deformaldehyde.settings import MEDIA_ROOT
from deformaldehyde.sitemap import StaticViewSitemap, ArticleSiteMap, \
    CategorySiteMap, TagSiteMap

sitemaps = {
    'static': StaticViewSitemap,
    'articles': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap
}


urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('dashboard.urls', namespace='dashboard')),
    url('', include('members.urls', namespace='members')),
    url('', include('comments.urls', namespace='comments')),
    url(r'^search/', include('haystack.urls')),
    re_path('media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
]

from django.conf.urls.static import static
from django.conf import settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/deformaldehyde/members/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views
from .forms import LoginForm

app_name = 'members'
urlpatterns = [

    path(r'article/<int:article_id>.html',
         views.ArticleDetailView.as_view(), name='article_detail'),
    url(r'^login/$', views.LoginView.as_view(success_url='/'), name='login', kwargs={'authentication_form': LoginForm}),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^member/$', login_required(views.BackStageView.as_view(), login_url='/'), name='member'),
    path(r'post', views.ArticleEditView.as_view(), name='article_post'),
    path(r'submitted', views.submitted, name='submitted'),
]

src/deformaldehyde/members/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth import get_user_model,password_validation
from django.utils.translation import gettext_lazy as _
from django.forms.models import ModelChoiceField

from ckeditor_uploader.widgets import CKEditorUploadingWidget

from dashboard.models import Category
from .models import Article

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.widgets.TextInput(attrs={'placeholder': "username", "class": "form-control"})
        self.fields['password'].widget = forms.widgets.PasswordInput(
            attrs={'placeholder': "password", "class": "form-control"})


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.widgets.TextInput(attrs={'id': 'user_login', 'class': 'input', 'size': '30', 'tabindex': '1'})
        self.fields['email'].widget = forms.widgets.EmailInput(attrs={'id': 'user_email', 'class': 'input', 'size': '30', 'tabindex': '2', "required": "required"})
        self.fields['password1'].widget = forms.widgets.PasswordInput(
            attrs={'id':"user_pwd1", 'class':"input", 'tabindex':"3", 'size': "30"})
        self.fields['password2'].widget = forms.widgets.PasswordInput(
            attrs={'id':"user_pwd2", 'class':"input", 'tabindex':"4", 'size': "30"})

    def clean_username(self):
        '''
        不允许用户名为中文
        '''
        username = self.cleaned_data.get('username')
        import re
        pattern = re.compile(u'[\u4e00-\u9fa5]+')
        if pattern.search(username):
            raise forms.ValidationError('用户名只能包含字母，数字和仅有的@/./+/-/_符号。')
        else:
            return username

    class Meta:
        model = get_user_model()
        fields = ("username", "email")


class AccountChangeForm(forms.Form):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'readonly': True,
        'style': 'width: 100%;',
        'id': 'user_login',
    }), required=False)
    nickname = forms.CharField(widget=forms.TextInput(attrs={
        'style': 'width: 100%;',
    }), required=False)
    mobile = forms.CharField(widget=forms.TextInput(attrs={
        'style': 'width: 100%;',
    }), required=False)
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'style': 'width: 100%;',
        'class': 'mid2',
        'readonly': True,
    }), required=False)
    site = forms.CharField(widget=forms.URLInput(attrs={
        'style': 'width: 100%;',
    }), required=False)
    qq = forms.CharField(widget=forms.TextInput(attrs={
        'style': 'width: 100%;',
    }), required=False)
    wechat = forms.CharField(widget=forms.TextInput(attrs={
        'style': 'width: 100%;',
    }), required=False)
    intro = forms.CharField(widget=forms.Textarea(attrs={
        'style': 'width: 100%;',
        'rows' : '5',
        'id': 'description',
    }), required=False)
    portrait = forms.ImageField(widget=forms.FileInput(attrs={
        'style': 'width: 100%;',
        'id': 'simple-local-avatar',
    }), required=False)
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'autofocus': True, 'id':"password",
                                          'class':"mid2",  'style': 'width: 100%;'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
        required=False
    )
    password2 = forms.CharField(
        label=_("Password (again)"),
        widget=forms.PasswordInput(attrs={'autofocus': True, 'id':"repsword",
                                          'class':"mid2",  'style': 'width: 100%;'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
        required=False
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if not password2:
            return
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        """Save the new password."""
        nickname = self.cleaned_data['nickname']
        mobile = self.cleaned_data['mobile']
        site = self.cleaned_data['site']
        password = self.cleaned_data["password1"]
        qq = self.cleaned_data['qq']
        wechat = self.cleaned_data['wechat']
        intro = self.cleaned_data['intro']
        portrait = self.cleaned_data['portrait']
        if nickname:
            self.user.nickname = nickname
        if mobile:
            self.user.mobile = mobile
        if password:
            self.user.set_password(password)
        if site:
            self.user.site = site
        if qq:
            self.user.qq = qq
        if wechat:
            self.user.wechat = wechat
        if intro:
            self.user.intro = intro
        if portrait:
            self.user.portrait = portrait
        if commit:
            self.user.save()
        return self.user


class ArticleModelForm(forms.ModelForm):
    title = forms.CharField(widget= forms.TextInput(attrs={'placeholder' : '必填'}),
                            error_messages={'unique': '该信息标题重复，请更换标题！'})
    content = forms.CharField(widget=CKEditorUploadingWidget())
    category = ModelChoiceField(queryset=Category.objects.all(),
                                widget=forms.Select(attrs={'class': 'postform'}),
                                empty_label='{0} 请选择信息分类 {0}'.format('-'*26))
    wechat = forms.CharField(widget= forms.TextInput(attrs={'placeholder' : '选填'}),
                             required=False)

    class Meta:
        model = Article
        fields = ['title', 'wechat', 'category', 'area_tags', 'tags','image', 'content']
        widgets= {
            'tags': forms.SelectMultiple(attrs={'class': 'postform'}),
            'area_tags': forms.SelectMultiple(attrs={'class': 'postform'}),
        }

src/deformaldehyde/members/views.py
from django.views.generic import DetailView

from django.contrib.auth import logout
from django.views.generic import FormView, RedirectView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.csrf import csrf_protect
from django.contrib import auth
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.views.decorators.debug import sensitive_post_parameters
from django.utils.http import is_safe_url
from django.views.generic import TemplateView
from django.shortcuts import render

from .models import Article
from .forms import RegisterForm, LoginForm, ArticleModelForm, AccountChangeForm
from dashboard.models import SiteSettings
from comments.forms import CommentForm
from deformaldehyde.utils import get_page

class ArticleDetailView(DetailView):
    template_name = 'members/article.html'
    model = Article
    context_object_name = 'article'
    pk_url_kwarg = 'article_id'

    def get_object(self):
        obj = super().get_object()
        obj.viewed()
        obj.image = Article.objects.get(id=int(self.kwargs[self.pk_url_kwarg])).image
        self.object = obj
        return obj

    def get_context_data(self, **kwargs):
        article_comments = self.object.comment_list()
        site_settings = SiteSettings.objects.get()

        kwargs['commentForm'] = CommentForm()
        kwargs['article_comments'] = article_comments
        kwargs['articles'] = Article.published.filter(ad_property=5)[:4]
        kwargs['sim_articles'] = Article.published.filter(category=kwargs['object'].category, ad_property=0)[:5]
        kwargs['best_articles'] = Article.published.filter(ad_property=0).order_by('-views')[:5]
        kwargs['wechat_pay_code'] = site_settings.wechat_pay_code
        kwargs['alipay_code'] = site_settings.alipay_code
        context = super().get_context_data(**kwargs)
        return context


class BackStageView(TemplateView):
    '''
    会员后台
    '''
    template_name = 'members/backstage.html'

    def get(self, request):
        user = request.user
        form = AccountChangeForm(user, initial={
            'username': user.username,
            'nickname': user.nickname,
            'mobile': user.mobile,
            'email': user.email,
            'site': user.site,
            'qq': user.qq,
            'wechat': user.wechat,
            'intro': user.intro,
            'portrait': user.portrait,
        })
        articles = user.article_set.all()
        particles, page_range = get_page(request, articles)
        context = {
            'user_change_form': form,
            'username': user.username,
            'nickname': user.nickname,
            'level': user.get_level_display,
            'email': user.email,
            'len_comments': user.comment_set.all().count(),
            'len_articles': articles.count(),
            'particles': particles,
            'page_range': page_range,
            'date_joined': user.date_joined,
            'last_login': user.last_login,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        user = request.user
        form = AccountChangeForm(user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            url = reverse('members:member')
            return HttpResponseRedirect('{}#usertab2'.format(url))
        else:
            print(form.errors)
            return render(request, self.template_name, {'user_change_form': form})


class RegisterView(FormView):
    '''
    注册
    '''
    form_class = RegisterForm
    template_name = 'members/register.html'

    def get_context_data(self, **kwargs):
        """
        Insert the form into the context dict.
        """
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        if self.request.user.is_authenticated:
            kwargs['user'] = self.request.user
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save(False)
        if not user.nickname:
            user.nickname = user.username
        user.is_staff = True
        user.save(True)
        url = reverse('members:login')
        return HttpResponseRedirect(url)


class LogoutView(RedirectView):
    '''
    登出
    '''
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super(LogoutView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        from deformaldehyde.utils import cache
        cache.clear()
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        redirect_to = self.request.META.get('HTTP_REFERER', '/')
        return redirect_to


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'members/login.html'
    success_url = '/'
    redirect_field_name = 'HTTP_REFERER'

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # redirect_to = self.request.GET.get(self.redirect_field_name, '/')
        redirect_to = self.request.META.get('HTTP_REFERER', '/')
        kwargs['redirect_to'] = redirect_to

        return super(LoginView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        form = AuthenticationForm(data=self.request.POST, request=self.request)

        if form.is_valid():
            from deformaldehyde.utils import cache
            if cache and cache is not None:
                cache.clear()
            print(self.redirect_field_name)
            auth.login(self.request, form.get_user())
            return super(LoginView, self).form_valid(form)
            # return HttpResponseRedirect('/')
        else:
            return render(self.request, self.template_name, {
                'form': form
            })


    def get_success_url(self):
        print(self.redirect_field_name)
        # redirect_to = self.request.POST.get(self.redirect_field_name)
        redirect_to = self.request.META.get('HTTP_REFERER')
        if reverse('members:login') in redirect_to:
            redirect_to = reverse('dashboard:index')
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


class ArticleEditView(TemplateView):
    template_name = 'members/article_post.html'

    def get(self, request, *args, **kwargs):
        form = ArticleModelForm()
        return render(request, self.template_name, {'article_form': form, 'form': LoginForm()})

    def post(self, request, *args, **kwargs):
        post = request.POST.copy()
        form = ArticleModelForm(post, request.FILES)
        if form.is_valid():
            form_cleaned_data = form.cleaned_data
            title = form_cleaned_data.get('title')
            wechat = form_cleaned_data.get('wechat')
            category = form_cleaned_data.get('category')
            area_tags = form_cleaned_data.get('area_tags')
            tags = form_cleaned_data.get('tags')
            content = form_cleaned_data.get('content')
            image = form_cleaned_data.get('image')
            dict_ = {
                'account': request.user,
                'title': title,
                'category': category,
                'content': content,
                'image': image,
            }
            if wechat:
                dict_['wechat'] = wechat
            article = Article.objects.create(**dict_)
            for tag in tags:
                article.tags.add(tag)
            for tag in area_tags:
                article.area_tags.add(tag)
            article.save(is_compress=True)

            return HttpResponseRedirect(reverse('members:submitted'))
        else:
            return render(request, self.template_name, {'article_form': form})

def submitted(request):
    return render(request, 'members/submitted.html')

src/deformaldehyde/members/templates/members/login.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 8]>
		<html xmlns="http://www.w3.org/1999/xhtml" class="ie8" lang="zh-CN">
	<![endif]-->
<!--[if !(IE 8) ]><!-->
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN">
<!--<![endif]-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>甲醛克星网 &lsaquo; 登录</title>
    <link rel="shortcut icon" href="{% static 'dashboard/images/favicon.jpg' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'dashboard/images/favicon.jpg' %}" />
    <link rel='stylesheet' id='dashicons-css' href="{% static 'members/css/dashicons.min.css' %}" type='text/css' media='all' />
    <link rel='stylesheet' id='buttons-css' href="{% static 'members/css/buttons.min.css' %}" type='text/css' media='all' />
    <link rel='stylesheet' id='forms-css' href="{% static 'members/css/forms.min.css' %}" type='text/css' media='all' />
    <link rel='stylesheet' id='l10n-css' href="{% static 'members/css/l10n.min.css' %}" type='text/css' media='all' />
    <link rel='stylesheet' id='login-css' href="{% static 'members/css/login.min.css' %}" type='text/css' media='all' />
    <link rel='stylesheet' id='open-social-style-css' href="{% static 'members/css/os.css' %}" type='text/css' media='all' />
    <style type="text/css">
        body {
            font-family: "Microsoft YaHei", Helvetica, Arial, Lucida Grande, Tahoma, sans-serif;
            background: url("{% static 'members/images/timg.jpg' %}");
            width: 100%;
            height: 100%;
        }

        .login h1 a {
            background: url("{% static 'dashboard/picture/logo.png' %}") no-repeat 0 0 transparent;
            width: 220px;
            height: 50px;
            padding: 0;
            margin: 0 auto 1em;
        }

        .login form,
        .login .message {
            background: #fff;
            background: rgba(255, 255, 255, 0.6);
            border-radius: 2px;
            border: 1px solid #fff;
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.8);
        }

        .login label {
            color: #000;
            font-weight: bold;
        }

        .login .message {
            color: #000;
        }

        #backtoblog a,
        #nav a {
            color: #fff !important;
        }
    </style>
    <meta name='robots' content='noindex,follow' />
</head>

<body class="login login-action-login wp-core-ui  locale-zh-cn">
    <div id="login">
        <h1><a href="{% url 'dashboard:index' %}" title="欢迎您光临本站！" tabindex="-1">甲醛克星网</a></h1>

        <form name="loginform" id="loginform" action="{% url 'members:login' %}" method="post">
            {% csrf_token %}
            <p>
                <label for="user_login">用户名或电子邮件地址<br />
                {{ form.username }}
                {{ form.username.errors }}
            </p>
            <p>
                <label for="user_pass">密码<br />
                {{ form.password }}
                {{ form.password.errors }}
            </p>
            <p class="forgetmenot">
                <label for="rememberme"><input name="rememberme" type="checkbox" id="rememberme" value="forever" /> 记住我的登录信息</label>
            </p>
            <p class="submit">
                <input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="登录" />
                <input type="hidden" name="redirect_to" value="/" />
                <input type="hidden" name="testcookie" value="1" />
            </p>
        </form>

        <p id="nav">
            <a href="{% url 'members:register' %}">注册</a> | <a href="">忘记密码？</a>
        </p>

        <p id="backtoblog"><a href="{% url 'dashboard:index' %}">&larr; Back to 甲醛克星网</a></p>

    </div>


    <script type='text/javascript'>
        /* <![CDATA[ */
        var open_social = {
            "status": "abc",
            "content": "def"
        };
        /* ]]> */
    </script>
    <script type='text/javascript' src="{% static 'members/js/os.js' %}"></script>
    <div class="clear"></div>
</body>

</html>

src/deformaldehyde/members/templates/members/register.html
{% extends 'share_layout/base.html' %}
{% load fullurl %}
{% load dashboard_extras %}

{% block header %}
    <title>注册 | 甲醛克星网</title>
{% endblock %}

{% block primary %}
    <style type="text/css">
        body {
          background: url({% fullstatic 'members/images/beijing001.jpg' %})
        }
    </style>
    <style type="text/css">
        #primary {
            width: 100%;
            height: 700px;
            box-shadow: none;
        }

        #primary .page {
            background: transparent !important;
            padding: 0 !important;
            border: none !important;
            box-shadow: none !important;
        }

        #primary .single-content {
            float: left;
            width: 50%;
            font-size: 16px;
            color: #fff;
            margin: 30px 0 0 0;
            padding: 10px 10px 10px 30px;
        }

        .reg-main {
            margin: 30px 0 0 0;
        }

        .user_reg {
            float: right;
            width: 70%;
        }

        .reg-page {
            position: relative;
            float: left;
            width: 50%;
            height: 500px;
            padding: 10px 30px 10px 10px;
            border-right: 1px dashed #ccc;
        }

        .reg-page p {
            text-indent: 0em;
        }

        p.user_error {
            position: fixed;
            top: 100px;
            left: 0;
            background: #fff;
            margin: 16px 0;
            padding: 10px 10px 0 10px;
            border-radius: 2px;
            border: 1px solid #f3f3f3;
        }

        .user_error .be-info {
            color: #ff0129;
            margin: 0 5px 0 0;
        }

        .shut-error {
            float: right;
            color: #e73c31;
            padding: 5px;
            display: block;
            cursor: pointer;
        }

        p.user_is {
            width: 300px;
            color: #fff;
            line-height: 40px;
            text-align: center;
            margin: 50px auto;
            padding: 12px;
        }

        .user_is a {
            background: #e73c31;
            color: #fff;
            padding: 5px 10px;
            border: 1px solid #e73c31;
            border-radius: 2px;
            -webkit-appearance: none;
        }

        .user_is a:hover {
            background: #fb5548;
            border: 1px solid #fb5548;
            transition: all 0.2s ease-in 0s;
        }

        .user_is img {
            margin: 0 auto;
        }

        .user_reg label {
            color: #fff;
            cursor: pointer;
        }

        .user_reg .input {
            background: #fff;
            width: 70%;
            margin: 5px 0;
            padding: 5px 10px;
            border: 1px solid #ddd;
            border-radius: 2px;
            -webkit-appearance: none;
        }

        .reg-page #submit {
            background: #e73c31;
            font-size: 16px;
            color: #fff;
            width: 100px;
            margin: 10px 10px 10px 0;
            padding: 6px;
            cursor: pointer;
            border: 1px solid #e73c31;
            border-radius: 2px;
            -webkit-appearance: none;
        }

        .reg-page #submit:hover {
            background: #fb5548;
            border: 1px solid #fb5548;
            transition: all 0.2s ease-in 0s;
        }

        .to-code a {
            background: #e73c31;
            color: #fff;
            padding: 6px;
            border: 1px solid #e73c31;
            border-radius: 2px;
            -webkit-appearance: none;
        }

        .to-code a:hover {
            background: #fb5548;
            border: 1px solid #fb5548;
            transition: all 0.2s ease-in 0s;
        }

        .droperror {
            color: #fff;
        }

        #scroll .scroll-c,
        .tg-site {
            display: none;
        }

        .reg-error {
            color: #fff;
            font-size: 16px;
            font-size: 1.6rem;
            text-align: center;
            margin: 50px 0;
        }

        @media screen and (max-width: 900px) {
            #primary .single-content {
                display: none;
            }
            .reg-page {
                width: 100%;
                padding: 10px;
                border-right: none;
            }
            .user_reg {
                float: inherit;
            }
            .user_reg {
                width: 100%;
            }
            .to-code {
                width: 90px;
                display: block;
            }
        }

        .si_captcha_small {
            margin: 0 0 10px 0;
        }
    </style>

    <div id="primary" class="content-reg">
        <main id="main" class="site-main" role="main">
            <article id="post-101" class="post-101 page type-page status-publish hentry qvw">
                <div class="reg-main">
                    <div class="reg-page">
                      {% if request.user.is_authenticated %}
                        <p class="user_is">
                            欢迎 <strong>{{ request.user.username }}</strong><br>
                            <a href="{% url "members:logout" %}" title="">退出登录</a>
                            &nbsp;&nbsp;<a href="{% url 'members:member' %}">用户中心</a>
                        </p>
                      {% else %}
                          <form name="registerform" method="post" action="{% url 'members:register' %}" class="user_reg">
                          {% csrf_token %}
                          {{ form.non_field_errors }}
                                <p>
                                    <label for="user_login">用户名 *<br />
                                        {{ form.username }}
                                    </label>
                                    {{ form.username.errors }}
                                </p>

                                <p>
                                    <label for="user_email">电子邮件地址 *<br />
                                        {{ form.email }}
                                    </label>
                                    {{ form.email.errors }}
                                </p>

                                <p>
                                    <label for="user_pwd1">密码(至少8位) *<br />
                                        {{ form.password1 }}
                                    </label>
                                    {{ form.password1.errors }}
                                </p>

                                <p>
                                    <label for="user_pwd2">重复密码 *<br />
                                        {{ form.password2 }}
                                    </label>
                                    {{ form.password2.errors }}
                                </p>


                                <p class="submit">
                                    <input type="hidden" name="user_reg" value="ok" />
                                    <input id="submit" name="submit" type="submit" value="提交注册" />
                                </p>
                           </form>
                        {% endif %}

                    </div>

                    <div class="entry-content">
                        <div class="single-content">
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </article>
        </main>
    </div>
{% endblock %}
